# Generated by Django 3.0.3 on 2020-02-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='main_url',
            new_name='main_link',
        ),
    ]
