# Generated by Django 3.0.3 on 2020-02-14 19:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date_click', models.DateField(default=datetime.date.today, verbose_name='Last date click')),
                ('today_click', models.IntegerField(default=1, verbose_name='Today click')),
                ('last_30_days', models.CharField(default='0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0', max_length=1000, verbose_name='Last 2')),
            ],
        ),
        migrations.CreateModel(
            name='URLObservation',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.Observation')),
            ],
            bases=('analytics.observation',),
        ),
        migrations.CreateModel(
            name='UserObservation',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.Observation')),
            ],
            bases=('analytics.observation',),
        ),
    ]
