# Generated by Django 3.0.3 on 2020-02-14 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_auto_20200214_1342'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='short_url',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='short_url.ShortURL'),
        ),
    ]
