# Generated by Django 3.0.3 on 2020-02-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_observation_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='today_click',
            field=models.IntegerField(default=0, verbose_name='Today click'),
        ),
    ]
