# Generated by Django 3.0.3 on 2020-02-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20200215_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='device',
            field=models.IntegerField(choices=[(0, 'Mobile'), (1, 'Desktop')], default=0, verbose_name='Device'),
        ),
    ]
