# Generated by Django 3.0.3 on 2020-02-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20200215_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userobservation',
            name='owner',
        ),
        migrations.AddField(
            model_name='userobservation',
            name='owner_ip',
            field=models.CharField(default='127.0.0.1', max_length=20, verbose_name='Owner IP'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='browser',
            field=models.IntegerField(choices=[(0, 'Chrome'), (1, 'Mozilla'), (2, 'Safari'), (3, 'IE'), (4, 'Opera'), (5, 'Others')], default=0, verbose_name='Browser'),
        ),
    ]
