# Generated by Django 3.0.3 on 2020-02-14 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20200215_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='create_date',
            field=models.DateField(default=datetime.date(2020, 2, 15), verbose_name='Create Date'),
        ),
    ]
