# Generated by Django 3.0.3 on 2020-02-16 00:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_auto_20200214_1342'),
        ('analytics', '0009_observation_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlobservation',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='userobservation',
            name='short_url',
        ),
        migrations.AddField(
            model_name='observation',
            name='short_url',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='short_url.ShortURL'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='create_date',
            field=models.DateField(default=datetime.date(2020, 2, 16), verbose_name='Create Date'),
        ),
    ]
