# Generated by Django 3.0.3 on 2020-02-16 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('short_url', '0002_auto_20200214_1342'),
        ('analytics', '0010_auto_20200216_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='short_url',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='short_url.ShortURL'),
        ),
    ]
